# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.16.0

pipelines:
  default:
    - step:
        caches:
          - node
        name: "build and test"
        script: 
          - npm install
          - npm run test
          - echo "Build and test step finished"
        services:
          - mongo
definitions:
  services:
    mongo:
      image: mongo 

